# Generated by Django 5.0.8 on 2026-09-14 11:51

import django.db.models.deletion
import documentmanager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('entity', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('entity_token', models.CharField(blank=True, max_length=255, null=True)),
                ('folder', models.CharField(blank=True, max_length=255, null=True)),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('location_url', models.URLField(blank=True, max_length=500, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('service', models.CharField(choices=[('hdd', 'HDD'), ('azure', 'Azure'), ('aws', 'AWS'), ('ftp', 'FTP')], default='hdd', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documentmanager.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=documentmanager.models.generate_token, max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Sended'), (3, 'Signed'), (4, 'Expired'), (-1, 'Error')], default=1)),
                ('error_report', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_signs', to=settings.AUTH_USER_MODEL)),
                ('document_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_signs_as_file', to='documentmanager.document')),
                ('document_file_signed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_signs_as_signed_file', to='documentmanager.document')),
            ],
            options={
                'verbose_name': 'Document Sign',
                'verbose_name_plural': 'Document Signs',
                'ordering': ['-created_at'],
            },
        ),
    ]
